
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayana Citra
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NIS = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        Kelas = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        TempatLahir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TanggalLahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(162, 159, 154));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 490, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("The Real Informatic Shool");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 50, 250, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 100);

        jPanel3.setBackground(new java.awt.Color(208, 206, 206));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btSave);
        btSave.setBounds(20, 10, 80, 30);

        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btDelete);
        btDelete.setBounds(120, 10, 80, 30);

        btClear.setText("CLEAR");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel3.add(btClear);
        btClear.setBounds(220, 10, 80, 30);

        btRefresh.setText("REFRESH");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btRefresh);
        btRefresh.setBounds(320, 10, 80, 30);

        btEdit.setText("EDIT");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel3.add(btEdit);
        btEdit.setBounds(430, 10, 80, 30);

        btPrint.setText("PRINT");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btPrint);
        btPrint.setBounds(530, 10, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(240, 120, 630, 50);

        jPanel5.setBackground(new java.awt.Color(208, 206, 206));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(10, 4, 150, 20);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 120, 200, 30);

        jPanel6.setBackground(new java.awt.Color(238, 64, 64));
        jPanel6.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(208, 206, 206));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "TempatLahir", "TanggalLahir", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 610, 490);

        jPanel6.add(jPanel4);
        jPanel4.setBounds(240, 80, 630, 510);

        jPanel2.setBackground(new java.awt.Color(208, 206, 206));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel4.setText("NIS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 180, 14);

        jLabel5.setText("Nama");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 70, 170, 14);

        jLabel6.setText("Jenis Kelamin");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 260, 180, 14);

        jLabel7.setText("Kelas");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 310, 180, 14);

        jLabel8.setText("Email");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 370, 180, 14);

        jLabel9.setText("Alamat");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 430, 180, 14);

        NIS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(NIS);
        NIS.setBounds(10, 30, 180, 30);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(Nama);
        Nama.setBounds(10, 90, 180, 30);

        buttonGroup1.add(Laki);
        Laki.setText("Laki - Laki");
        jPanel2.add(Laki);
        Laki.setBounds(10, 280, 71, 23);

        buttonGroup1.add(Perempuan);
        Perempuan.setText("Perempuan");
        jPanel2.add(Perempuan);
        Perempuan.setBounds(100, 280, 79, 23);

        Kelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(Kelas);
        Kelas.setBounds(10, 330, 180, 30);

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(Email);
        Email.setBounds(10, 390, 180, 30);

        Alamat.setColumns(20);
        Alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 450, 180, 70);

        jLabel10.setText("Tempat Lahir");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 180, 14);
        jPanel2.add(TempatLahir);
        TempatLahir.setBounds(10, 150, 180, 30);

        jLabel11.setText("Tanggal Lahir");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 190, 180, 14);
        jPanel2.add(TanggalLahir);
        TanggalLahir.setBounds(10, 210, 180, 30);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(20, 60, 200, 530);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 100, 900, 610);

        setBounds(0, 0, 898, 746);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(TanggalLahir.getDate());
        String JK = "";
        if (Laki.isSelected()){
            
        }else{
            JK = "L";
        }
        if (Perempuan.isSelected())
            JK = "P";
        
        if(NIS.getText().equals("") || Nama.getText().equals("") || TanggalLahir.equals("") || JK.equals("") || Kelas.getText().equals("") || Email.getText().equals("") || TempatLahir.getText().equals("") || Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
            String SQL = "INSERT INTO t_siswa VALUES ('"+NIS.getText()+"', '"+Nama.getText()+"', '"+tanggal+"', '"+JK+"', '"+Kelas.getText()+"', '"+Email.getText()+"', '"+TempatLahir.getText()+"', '"+Alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        /*if ("".equals(NIS.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(Nama.getText()) || "".equals(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
                if (Laki.isSelected()) {
                    JK = "L";
                } else {
                    JK = "P";
                }
            
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat)"
                    + "VALUES('"+NIS.getText()+"','"+Nama.getText()+"','"+JK+"','"+Kelas.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }*/
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            String NIS = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        NIS.setText("");
        Kelas.setText("");
        buttonGroup1.clearSelection();
        Email.setText("");
        Alamat.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        if ("".equals(NIS.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(Nama.getText()) || "".equals(Email.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
                if (Laki.isSelected()) {
                    JK = "L";
                } else {
                    JK = "P";
                }
            
            String SQL = "UPDATE t_siswa SET"+"WHERE NamaSiswa='"+Nama.getText()+"','"+"WHERE JenisKelamin='"+JK+"','"+"WHERE Kelas='"+Kelas.getText()+"','"+"WHERE Email='"+Email.getText()+"','"+"WHERE Alamat='"+Alamat.getText()+"','"+"WHERE NIS='"+NIS.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            NIS.setText(jTable1.getValueAt(baris, 0).toString());
            Nama.setText(jTable1.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals(jTable1.getValueAt(baris, 2).toString())) {
                Laki.setSelected(true);
            }else {
                Perempuan.setSelected(true);
            }
            Kelas.setText(jTable1.getValueAt(baris, 3).toString());
            Email.setText(jTable1.getValueAt(baris, 4).toString());
            Alamat.setText(jTable1.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");
        
        try {
            jTable1.print(jTable1.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    public void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel (null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    JenisKelamin = "Laki - Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
        
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Kelas;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Perempuan;
    private com.toedter.calendar.JDateChooser TanggalLahir;
    private javax.swing.JTextField TempatLahir;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
